const std = @import("std");

pub fn getAndroidTriple(target: std.Target) error{InvalidAndroidTarget}![]const u8 {
    if (target.abi != .android and target.abi != .androideabi) {
        return error.InvalidAndroidTarget;
    }

    return switch (target.cpu.arch) {
        .x86 => "i686-linux-android",
        .x86_64 => "x86_64-linux-android",
        .arm => "arm-linux-androideabi",
        .aarch64 => "aarch64-linux-android",
        else => error.InvalidAndroidTarget,
    };
}

pub fn getOutputDir(target: std.Target) error{UnsupportedArchitecture}![]const u8 {
    return switch (target.cpu.arch) {
        .aarch64 => "arm64-v8a",
        .arm => "armeabi-v7a",
        .x86 => "x86",
        .x86_64 => "x86_64",
        else => error.UnsupportedArchitecture,
    };
}

pub fn createLibC(
    b: *std.Build,
    system_target: []const u8,
    android_api_version: u32,
    ndk_sysroot_path: []const u8,
) std.Build.LazyPath {
    const libc_file_format =
        \\# Generated by Chuchu build. DO NOT EDIT.
        \\
        \\include_dir={[include_dir]s}
        \\
        \\sys_include_dir={[sys_include_dir]s}
        \\
        \\crt_dir={[crt_dir]s}
        \\
        \\msvc_lib_dir=
        \\
        \\kernel32_lib_dir=
        \\
        \\gcc_dir=
    ;

    const include_dir = b.fmt("{s}/usr/include", .{ndk_sysroot_path});
    const sys_include_dir = b.fmt("{s}/usr/include/{s}", .{ ndk_sysroot_path, system_target });
    const crt_dir = b.fmt("{s}/usr/lib/{s}/{d}", .{ ndk_sysroot_path, system_target, android_api_version });

    const libc_file_contents = b.fmt(libc_file_format, .{
        .include_dir = include_dir,
        .sys_include_dir = sys_include_dir,
        .crt_dir = crt_dir,
    });

    const filename = b.fmt("android-libc-{s}-{d}.conf", .{ system_target, android_api_version });
    const write_file = b.addWriteFiles();
    return write_file.add(filename, libc_file_contents);
}
